// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/hosted-rest-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"agent_health | agent_sandbox | agent_user_detail | agent_user_list | app_user | app_user_login | app_user_session | app_user_total | app_user_verify | authentication | collection | collection_record | collection_record_list | custom | legacy | legacy_mutation | legacy_unknown | legacy_unknown_list | legacy_user | legacy_user_list | login | register"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.HostedRestSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "hosted-rest_list",
		Description: "List records from HostedRest. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "hosted-rest_load",
		Description: "Load a single record from HostedRest. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.HostedRestSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.HostedRestSDK, name string) (sdk.HostedRestEntity, error) {
	switch strings.ToLower(name) {
	case "agent_health":
		return client.AgentHealth(nil), nil
	case "agent_sandbox":
		return client.AgentSandbox(nil), nil
	case "agent_user_detail":
		return client.AgentUserDetail(nil), nil
	case "agent_user_list":
		return client.AgentUserList(nil), nil
	case "app_user":
		return client.AppUser(nil), nil
	case "app_user_login":
		return client.AppUserLogin(nil), nil
	case "app_user_session":
		return client.AppUserSession(nil), nil
	case "app_user_total":
		return client.AppUserTotal(nil), nil
	case "app_user_verify":
		return client.AppUserVerify(nil), nil
	case "authentication":
		return client.Authentication(nil), nil
	case "collection":
		return client.Collection(nil), nil
	case "collection_record":
		return client.CollectionRecord(nil), nil
	case "collection_record_list":
		return client.CollectionRecordList(nil), nil
	case "custom":
		return client.Custom(nil), nil
	case "legacy":
		return client.Legacy(nil), nil
	case "legacy_mutation":
		return client.LegacyMutation(nil), nil
	case "legacy_unknown":
		return client.LegacyUnknown(nil), nil
	case "legacy_unknown_list":
		return client.LegacyUnknownList(nil), nil
	case "legacy_user":
		return client.LegacyUser(nil), nil
	case "legacy_user_list":
		return client.LegacyUserList(nil), nil
	case "login":
		return client.Login(nil), nil
	case "register":
		return client.Register(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
